# Generated by Django 4.1.1 on 2022-09-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('is_vip', models.BooleanField()),
                ('password', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('MDL', 'Moldavian Leu')], default='MDL', max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='bar_code',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='E_Shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='BagItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('bag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='E_Shop.bag')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='E_Shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='bag',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='E_Shop.client'),
        ),
        migrations.AddField(
            model_name='bag',
            name='cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='E_Shop.money'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='E_Shop.money'),
        ),
    ]
